import {jobs} from "./data.js";import {getSavedIds,getApplications,getTheme,setTheme,toggleSaved} from "./storage.js";
export function initShell(){document.documentElement.dataset.theme=getTheme();const theme=document.getElementById("themeToggle");if(theme){theme.textContent=getTheme()==="dark"?"☀":"☾";theme.addEventListener("click",()=>{const next=getTheme()==="dark"?"light":"dark";setTheme(next);document.documentElement.dataset.theme=next;theme.textContent=next==="dark"?"☀":"☾"})}
const menu=document.getElementById("menuToggle"),links=document.getElementById("navLinks");menu?.addEventListener("click",()=>{const open=links.classList.toggle("open");menu.setAttribute("aria-expanded",open)});
updateCounts();window.addEventListener("storage",updateCounts)}
export function updateCounts(){const saved=document.getElementById("savedCount"),apps=document.getElementById("applicationCount");if(saved)saved.textContent=getSavedIds().length;if(apps)apps.textContent=getApplications().length}
export function toast(message,type="success"){const region=document.getElementById("toastRegion");if(!region)return;const el=document.createElement("div");el.className=`toast ${type}`;el.innerHTML=`<strong>${type==="success"?"✓":type==="error"?"!":"i"}</strong><span>${message}</span>`;region.appendChild(el);setTimeout(()=>el.remove(),3500)}
export function getJob(id){return jobs.find(j=>j.id===Number(id))}
export function formatDate(date){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(`${date}T00:00:00`))}
export function jobCard(job){const saved=getSavedIds().includes(job.id);return `<article class="job-card"><div class="job-card-top"><div class="job-heading"><span class="company-logo ${job.logoClass}">${job.logo}</span><div><h3>${job.title}</h3><p>${job.company}</p></div></div><button class="save-btn ${saved?"saved":""}" data-save="${job.id}" aria-label="${saved?"Remove saved job":"Save job"}">${saved?"♥":"♡"}</button></div><div class="job-location"><span>⌖ ${job.location}</span><span>• ${job.type}</span><span>• ${job.experience}</span></div><p class="job-description">${job.description}</p><div class="job-tags">${job.skills.slice(0,3).map(s=>`<span class="skill-tag">${s}</span>`).join("")}</div><div class="job-footer"><div><div class="salary">${job.salary}</div><div class="posted">${relativePosted(job.posted)}</div></div></div><div class="card-actions"><button class="btn btn-outline" data-details="${job.id}">View Details</button><button class="btn btn-primary" data-apply="${job.id}">Apply Now</button></div></article>`}
function relativePosted(date){const days=Math.max(0,Math.round((Date.now()-new Date(`${date}T00:00:00`))/86400000));return days===0?"Posted today":days===1?"Posted yesterday":`Posted ${days} days ago`}
export function bindJobActions(root=document){root.addEventListener("click",e=>{const save=e.target.closest("[data-save]");if(save){const nowSaved=toggleSaved(save.dataset.save);save.classList.toggle("saved",nowSaved);save.textContent=nowSaved?"♥":"♡";save.setAttribute("aria-label",nowSaved?"Remove saved job":"Save job");updateCounts();toast(nowSaved?"Job saved to your shortlist.":"Job removed from saved jobs.","info")}});
}
export function renderJobDetails(job,container,onApply){container.innerHTML=`<div class="modal-job-header"><span class="company-logo ${job.logoClass}">${job.logo}</span><div><h2 id="jobModalTitle">${job.title}</h2><p>${job.company} · ${job.location}</p></div></div><div class="detail-meta"><span>⌖ ${job.location}</span><span>◷ ${job.type}</span><span>◆ ${job.experience}</span><span>▣ ${job.salary}</span><span>Deadline: ${formatDate(job.deadline)}</span></div><div class="detail-section"><h3>About the role</h3><p>${job.description}</p></div><div class="detail-section"><h3>Responsibilities</h3><ul>${job.responsibilities.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="detail-section"><h3>Requirements</h3><ul>${job.requirements.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="detail-section"><h3>Skills</h3><div class="job-tags">${job.skills.map(x=>`<span class="skill-tag">${x}</span>`).join("")}</div></div><div class="detail-section"><h3>Benefits</h3><ul>${job.benefits.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="modal-actions"><button class="btn btn-primary" id="detailApply">Apply for this job →</button><button class="btn btn-outline" data-save="${job.id}">${getSavedIds().includes(job.id)?"♥ Saved":"♡ Save Job"}</button></div>`;container.querySelector("#detailApply").addEventListener("click",()=>onApply(job))}
export function openModal(id){document.getElementById(id)?.classList.remove("hidden");document.body.classList.add("modal-open")}
export function closeModal(id){document.getElementById(id)?.classList.add("hidden");document.body.classList.remove("modal-open")}
export function bindModals(){document.addEventListener("click",e=>{const close=e.target.closest("[data-close-modal]");if(close)closeModal(close.dataset.closeModal);if(e.target.classList.contains("modal-backdrop"))e.target.classList.add("hidden")})}
export function applicationForm(job,submit){return `<div class="application-intro"><span class="eyebrow">Application</span><h2 id="applicationTitle">Apply: ${job.title}</h2><p>${job.company} · ${job.location} · ${job.salary}</p></div><form id="applicationForm" class="form-card" novalidate><div class="form-grid"><div class="form-field"><label for="appName">Full Name *</label><input id="appName" name="name" type="text" minlength="2" maxlength="80" required><small class="field-error"></small></div><div class="form-field"><label for="appEmail">Email *</label><input id="appEmail" name="email" type="email" required><small class="field-error"></small></div><div class="form-field"><label for="appPhone">Phone Number *</label><input id="appPhone" name="phone" type="tel" minlength="7" maxlength="20" required><small class="field-error"></small></div><div class="form-field"><label for="appResume">Resume *</label><input id="appResume" name="resume" class="file-input" type="file" accept=".pdf,.doc,.docx" required><small class="field-error"></small></div><div class="form-field full-span"><label for="appLinkedIn">LinkedIn Profile *</label><input id="appLinkedIn" name="linkedin" type="url" placeholder="https://www.linkedin.com/in/your-name" required><small class="field-error"></small></div><div class="form-field full-span"><label for="appGithub">GitHub Profile *</label><input id="appGithub" name="github" type="url" placeholder="https://github.com/your-username" required><small class="field-error"></small></div><div class="form-field full-span"><label for="appCover">Cover Letter * <span class="tiny-note">(100–1500 characters)</span></label><textarea id="appCover" name="cover" rows="7" minlength="100" maxlength="1500" required></textarea><small class="field-error"></small></div></div><button class="btn btn-primary full-width" type="submit">Submit Application →</button></form>`}
export function validateApplication(form){let ok=true;form.querySelectorAll(".form-field").forEach(f=>{f.classList.remove("invalid");f.querySelector(".field-error").textContent=""});const set=(id,msg)=>{const el=form.querySelector(`#${id}`),field=el?.closest(".form-field");if(field){field.classList.add("invalid");field.querySelector(".field-error").textContent=msg;ok=false}};const name=form.querySelector("#appName");if(!name.value.trim())set("appName","Please enter your full name.");else if(name.value.trim().length<2)set("appName","Name must contain at least 2 characters.");const email=form.querySelector("#appEmail");if(!email.value.trim())set("appEmail","Please enter your email.");else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value.trim()))set("appEmail","Please enter a valid email address.");const phone=form.querySelector("#appPhone");if(!phone.value.trim())set("appPhone","Phone number is required.");else if(!/^[+()\d\s-]{7,20}$/.test(phone.value.trim()))set("appPhone","Please enter a valid phone number.");const resume=form.querySelector("#appResume");if(!resume.files.length)set("appResume","Please select a resume file.");else if(!/\.(pdf|doc|docx)$/i.test(resume.files[0].name))set("appResume","Resume must be PDF, DOC or DOCX.");for(const id of ["appLinkedIn","appGithub"]){const el=form.querySelector(`#${id}`);try{const url=new URL(el.value);if(!["http:","https:"].includes(url.protocol))throw 0;if(id==="appLinkedIn"&&!url.hostname.includes("linkedin.com"))throw 0;if(id==="appGithub"&&!url.hostname.includes("github.com"))throw 0}catch{set(id,id==="appLinkedIn"?"Please enter a valid LinkedIn URL.":"Please enter a valid GitHub URL.")}}const cover=form.querySelector("#appCover");if(cover.value.trim().length<100)set("appCover","Cover letter must contain at least 100 characters.");else if(cover.value.trim().length>1500)set("appCover","Cover letter cannot exceed 1500 characters.");return ok}
export function wireApplication(job){const form=document.getElementById("applicationForm");form.addEventListener("submit",e=>{e.preventDefault();if(!validateApplication(form)){toast("Please fix the highlighted fields.","error");return}submitApplication(form,job);})}
function submitApplication(form,job){const data=new FormData(form);import("./storage.js").then(({addApplication,uid})=>{addApplication({id:uid(),applicantName:data.get("name").trim(),email:data.get("email").trim(),phone:data.get("phone").trim(),coverLetter:data.get("cover").trim(),resumeName:data.get("resume").name,linkedin:data.get("linkedin").trim(),github:data.get("github").trim(),jobId:job.id,jobTitle:job.title,company:job.company,applicationDate:new Date().toISOString(),status:"Submitted"});closeModal("applicationModal");updateCounts();toast("Application submitted successfully!");})}
export function openApplication(job){const wrap=document.getElementById("applicationFormWrap");if(!wrap)return;wrap.innerHTML=applicationForm(job);openModal("applicationModal");wireApplication(job)}
initShell();bindJobActions();bindModals();
if(document.getElementById("featuredJobs")){document.getElementById("featuredJobs").innerHTML=jobs.slice(0,3).map(jobCard).join("");document.getElementById("heroSearch")?.addEventListener("submit",e=>{e.preventDefault();const q=document.getElementById("heroKeyword").value.trim(),l=document.getElementById("heroLocation").value.trim();location.href=`jobs.html?search=${encodeURIComponent([q,l].filter(Boolean).join(" "))}`});document.querySelectorAll("[data-search]").forEach(b=>b.addEventListener("click",()=>location.href=`jobs.html?search=${encodeURIComponent(b.dataset.search)}`))}
