import {jobs} from "./data.js";import {getJob,jobCard,renderJobDetails,openModal,openApplication,closeModal,toast,bindJobActions,bindModals,initShell} from "./app.js";
initShell();bindJobActions();bindModals();
const els={grid:document.getElementById("jobGrid"),search:document.getElementById("jobSearch"),category:document.getElementById("categoryFilter"),location:document.getElementById("locationFilter"),type:document.getElementById("typeFilter"),experience:document.getElementById("experienceFilter"),salary:document.getElementById("salaryFilter"),sort:document.getElementById("sortJobs"),count:document.getElementById("resultsCount"),loading:document.getElementById("loadingState"),empty:document.getElementById("emptyState"),pagination:document.getElementById("pagination")};
let filtered=[...jobs],page=1;const perPage=6;
const params=new URLSearchParams(location.search);if(params.get("search"))els.search.value=params.get("search");if(params.get("category"))els.category.value=params.get("category");
function applyFilters(){const q=els.search.value.trim().toLowerCase();filtered=jobs.filter(j=>(!q||[j.title,j.company,j.location,j.category,...j.skills].join(" ").toLowerCase().includes(q))&&(!els.category.value||j.category===els.category.value)&&(!els.location.value||j.location===els.location.value)&&(!els.type.value||j.type===els.type.value)&&(!els.experience.value||j.experience===els.experience.value)&&j.salaryMin>=Number(els.salary.value));sortJobs();page=1;render()}
function sortJobs(){const s=els.sort.value;filtered.sort((a,b)=>s==="latest"?new Date(b.posted)-new Date(a.posted):s==="oldest"?new Date(a.posted)-new Date(b.posted):s==="salary-desc"?b.salaryMax-a.salaryMax:s==="salary-asc"?a.salaryMin-b.salaryMin:a.title.localeCompare(b.title))}
function render(){els.loading.classList.add("hidden");els.count.textContent=`${filtered.length} job${filtered.length!==1?"s":""} found`;els.empty.classList.toggle("hidden",filtered.length>0);els.grid.classList.toggle("hidden",filtered.length===0);if(!filtered.length){els.pagination.innerHTML="";return}const total=Math.ceil(filtered.length/perPage);if(page>total)page=total;const slice=filtered.slice((page-1)*perPage,page*perPage);els.grid.innerHTML=slice.map(jobCard).join("");renderPagination(total)}
function renderPagination(total){els.pagination.innerHTML=Array.from({length:total},(_,i)=>`<button class="page-btn ${i+1===page?"active":""}" data-page="${i+1}">${i+1}</button>`).join("");if(total>1)els.pagination.innerHTML+=`<button class="page-btn" data-page="${page+1}" ${page===total?"disabled":""}>Next</button>`;els.pagination.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>{const p=Number(b.dataset.page);if(p>=1&&p<=total){page=p;render();window.scrollTo({top:document.querySelector(".jobs-layout").offsetTop-90,behavior:"smooth"})}}))}
document.addEventListener("click",e=>{const d=e.target.closest("[data-details]"),a=e.target.closest("[data-apply]");if(d){const job=getJob(d.dataset.details);renderJobDetails(job,document.getElementById("jobDetails"),openApplication);openModal("jobModal")}if(a){const job=getJob(a.dataset.apply);openApplication(job)}});
[els.search,els.category,els.location,els.type,els.experience,els.salary].forEach(el=>el.addEventListener(el===els.search?"input":"change",applyFilters));els.sort.addEventListener("change",applyFilters);
document.getElementById("resetFilters").addEventListener("click",()=>{els.search.value="";els.category.value="";els.location.value="";els.type.value="";els.experience.value="";els.salary.value="0";els.sort.value="latest";applyFilters()});document.getElementById("emptyReset").addEventListener("click",()=>document.getElementById("resetFilters").click());
document.getElementById("openFilters")?.addEventListener("click",()=>document.getElementById("filterPanel").classList.add("open"));document.getElementById("closeFilters")?.addEventListener("click",()=>document.getElementById("filterPanel").classList.remove("open"));
setTimeout(applyFilters,450);